<?xml version="1.0"?>
<robot name="fourWD" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
	<xacro:arg name="with_cam" default="false" />
	<xacro:arg name="with_fisheyes" default="true" />
	<xacro:arg name="with_ydlidar" default="true" />

	<xacro:arg name="cam_x" default="0" />
	<xacro:arg name="cam_y" default="0" />
	<xacro:arg name="cam_z" default="0" />
	<xacro:arg name="cam_roll" default="0" />
	<xacro:arg name="cam_pitch" default="0" />
	<xacro:arg name="cam_yaw" default="0" />
	<xacro:arg name="cam_W" default="320" />
	<xacro:arg name="cam_H" default="240" />
	<xacro:arg name="cam_focal" default="3.6" />
	<xacro:arg name="cam_hfov" default="1.3962634" />

	<xacro:arg name="yl_x" default="0.0" />
	<xacro:arg name="yl_y" default="0.0" />
	<xacro:arg name="yl_z" default="0.0" />
	<xacro:arg name="yl_roll" default="0.0" />
	<xacro:arg name="yl_pitch" default="0.0" />
	<xacro:arg name="yl_yaw" default="0.0" />
	<xacro:arg name="yl_max_range" default="2.0" />
	<xacro:arg name="yl_min_range" default="0.1" />
	<xacro:arg name="yl_samples" default="720" />
	<xacro:arg name="yl_min_angle" default="-3.14159" />
	<xacro:arg name="yl_max_angle" default="3.14159" />
	
	
	


  <xacro:include filename="$(find uri_soft_gazebo_differential_drive)/urdf/differential_drive_base.urdf.xacro" /> 
  <xacro:include filename="$(find uri_soft_gazebo_differential_drive)/urdf/fisheyes.urdf.xacro" /> 
  <xacro:include filename="$(find uri_soft_gazebo_differential_drive)/urdf/ydlidar.urdf.xacro" /> 
  <xacro:include filename="$(find uri_soft_gazebo_differential_drive)/urdf/cam.urdf.xacro" /> 

<!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="1.0 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="Yellow">
    <color rgba="0.0 1.0 1.0 1.0"/>
  </material>

  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>


  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="M_PI_4" value="0.78539816339" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />

  <!-- Main body length, width and height -->
  <!-- Main Body Box base   -->
  <xacro:property name="base_length" value="0.22" /> 
  <xacro:property name="base_width" value="0.145" />
  <xacro:property name="base_height" value="0.09" /> 
  <xacro:property name="base_mass" value="0.7" /> <!-- in kg-->


  <!-- Wheels -->
  <xacro:property name="wheel_radius" value="0.032" /> 
  <xacro:property name="wheel_height" value="0.025" />
  <xacro:property name="wheel_mass" value="0.03" /> --> <!-- in kg-->
  


  <!-- here starts the real definition of the robot -->
	<xacro:differential_drive_base
		base_link="base_link"
		base_length="${base_length}"
		base_width="${base_width}"
		base_height="${base_height}"
		base_mass="${base_mass}"
		wheel_radius="${wheel_radius}"
		wheel_height="${wheel_height}"
		wheel_mass="${wheel_mass}"/>


	<xacro:if value="$(arg with_fisheyes)">
		<xacro:fisheyes parent="base_link" x="0" y="0" z="${base_height/2}" roll="0" pitch="0" yaw="0"/>
	</xacro:if>

	<xacro:if value="$(arg with_ydlidar)">
		<xacro:ydlidar parent="base_link"
			x="$(arg yl_x)"
			y="$(arg yl_y)"
			z="${$(arg yl_z)+base_height/2}"
			roll="$(arg yl_roll)"
			pitch="$(arg yl_pitch)"
			yaw="$(arg yl_yaw)"
			max_range="$(arg yl_max_range)"
			min_range="$(arg yl_min_range)"
			samples="$(arg yl_samples)"
			min_angle="$(arg yl_min_angle)"
			max_angle="$(arg yl_max_angle)"
		/>
	</xacro:if>

	<xacro:if value="$(arg with_cam)">
		<xacro:cam parent="base_link"
			x="$(arg cam_x)"
			y="$(arg cam_y)"
			z="${$(arg cam_z)+base_height/2}"
			roll="$(arg cam_roll)"
			pitch="$(arg cam_pitch)"
			yaw="$(arg cam_yaw)"
			W="$(arg cam_W)"
			H="$(arg cam_H)"
			hfov="$(arg cam_hfov)"
			focal="$(arg cam_focal)"
		/>
			
	</xacro:if>

</robot>
